eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

some:
  thing:
    value: efgh

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SCHOOL_A?useUnicode=yes&characterEncoding=UTF-8