eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-jenkins-dock:8761/eureka/

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-dock:3306/SCHOOL_A?useUnicode=yes&characterEncoding=UTF-8